# Site settings
title: Every Ring Has a Summer
baseurl: ""
url: "" # default is empty

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services - just leave empty to disable it
google_analytics:
disqus_shortname: "weatherwaxed"

# Fancy URL stuff
permalink: /:month/:day/:title/
gems:
  - jekyll-redirect-from
